export const statusOptions = [
  { label: '启用', value: 'ACTIVE' },
  { label: '停用', value: 'INACTIVE' },
];

export const deviceStatusOptions = [
  { label: '在线', value: 'ONLINE' },
  { label: '离线', value: 'OFFLINE' },
  { label: '维护中', value: 'MAINTENANCE' },
  { label: '故障', value: 'ERROR' },
];

const canteenReference = {
  referenceKey: 'canteens',
  endpoint: '/api/v1/canteens',
  valueKey: 'id',
  labelKey: 'name',
  emptyMessage: '请先维护餐厅资料',
  errorMessage: '餐厅选项加载失败',
  placeholder: '请选择餐厅',
};

const stallReference = {
  referenceKey: 'stalls',
  endpoint: '/api/v1/stalls',
  valueKey: 'id',
  labelKey: 'name',
  emptyMessage: '请先维护档口资料',
  errorMessage: '档口选项加载失败',
  placeholder: '请选择档口',
};

export const masterDataPages = {
  canteens: {
    title: '餐厅管理',
    description: '维护企业不同城市和园区的餐厅基础资料，为档口、设备和后续交易归属提供基础。',
    endpoint: '/api/v1/canteens',
    idField: 'id',
    statusOptions,
    columns: [
      { key: 'canteen_code', label: '餐厅编码' },
      { key: 'name', label: '餐厅名称' },
      { key: 'city', label: '城市' },
      { key: 'location', label: '位置' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'canteen_code', label: '餐厅编码', required: true },
      { key: 'name', label: '餐厅名称', required: true },
      { key: 'city', label: '城市', required: true },
      { key: 'location', label: '位置', required: true },
      { key: 'status', label: '状态', type: 'select', options: statusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { status: 'ACTIVE' },
  },
  stalls: {
    title: '档口管理',
    description: '维护餐厅内不同经营档口，建立档口与餐厅的归属关系。',
    endpoint: '/api/v1/stalls',
    idField: 'id',
    statusOptions,
    columns: [
      { key: 'stall_code', label: '档口编码' },
      { key: 'canteen_id', label: '餐厅', type: 'reference', referenceKey: 'canteens' },
      { key: 'name', label: '档口名称' },
      { key: 'category', label: '品类' },
      { key: 'floor', label: '楼层' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'stall_code', label: '档口编码', required: true },
      { key: 'canteen_id', label: '餐厅', type: 'reference', reference: canteenReference, required: true },
      { key: 'name', label: '档口名称', required: true },
      { key: 'category', label: '品类', required: true },
      { key: 'floor', label: '楼层' },
      { key: 'status', label: '状态', type: 'select', options: statusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { status: 'ACTIVE' },
  },
  dishes: {
    title: '菜品管理',
    description: '维护档口下售卖菜品、价格和可售状态，阶段 1 不涉及下单和库存。',
    endpoint: '/api/v1/dishes',
    idField: 'id',
    statusOptions,
    columns: [
      { key: 'dish_code', label: '菜品编码' },
      { key: 'stall_id', label: '档口', type: 'reference', referenceKey: 'stalls' },
      { key: 'name', label: '菜品名称' },
      { key: 'category', label: '品类' },
      { key: 'unit_price', label: '单价', type: 'money' },
      { key: 'is_available', label: '可售', type: 'boolean' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'dish_code', label: '菜品编码', required: true },
      { key: 'stall_id', label: '档口', type: 'reference', reference: stallReference, required: true },
      { key: 'name', label: '菜品名称', required: true },
      { key: 'category', label: '品类', required: true },
      { key: 'unit_price', label: '单价', type: 'number', step: '0.01', required: true },
      { key: 'is_available', label: '是否可售', type: 'checkbox' },
      { key: 'status', label: '状态', type: 'select', options: statusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { is_available: true, status: 'ACTIVE' },
  },
  mealPackages: {
    title: '套餐管理',
    description: '维护档口套餐基础资料。套餐与菜品明细关系已在数据库预留，页面阶段 1 先维护套餐主体。',
    endpoint: '/api/v1/meal-packages',
    idField: 'id',
    statusOptions,
    columns: [
      { key: 'package_code', label: '套餐编码' },
      { key: 'stall_id', label: '档口', type: 'reference', referenceKey: 'stalls' },
      { key: 'name', label: '套餐名称' },
      { key: 'package_price', label: '套餐价', type: 'money' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'package_code', label: '套餐编码', required: true },
      { key: 'stall_id', label: '档口', type: 'reference', reference: stallReference, required: true },
      { key: 'name', label: '套餐名称', required: true },
      { key: 'package_price', label: '套餐价', type: 'number', step: '0.01', required: true },
      { key: 'status', label: '状态', type: 'select', options: statusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { status: 'ACTIVE' },
  },
  employees: {
    title: '员工管理',
    description: '维护员工基础资料和卡号绑定，为后续模拟员工刷卡消费做准备。',
    endpoint: '/api/v1/employees',
    idField: 'id',
    statusOptions,
    columns: [
      { key: 'employee_no', label: '员工编号' },
      { key: 'name', label: '姓名' },
      { key: 'department', label: '部门' },
      { key: 'employee_type', label: '员工类型' },
      { key: 'card_no', label: '卡号' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'employee_no', label: '员工编号', required: true },
      { key: 'name', label: '姓名', required: true },
      { key: 'department', label: '部门', required: true },
      {
        key: 'employee_type',
        label: '员工类型',
        type: 'select',
        options: [
          { label: '正式员工', value: 'FULL_TIME' },
          { label: '合同工', value: 'CONTRACTOR' },
          { label: '外包员工', value: 'OUTSOURCED' },
          { label: '实习生', value: 'INTERN' },
          { label: '管理人员', value: 'MANAGEMENT' },
        ],
      },
      { key: 'card_no', label: '卡号' },
      { key: 'phone', label: '手机号' },
      { key: 'status', label: '状态', type: 'select', options: statusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { employee_type: 'FULL_TIME', status: 'ACTIVE' },
  },
  visitors: {
    title: '访客管理',
    description: '维护访客基础信息，为后续访客扫码支付和接待消费场景提供对象资料。',
    endpoint: '/api/v1/visitors',
    idField: 'id',
    statusOptions,
    columns: [
      { key: 'visitor_no', label: '访客编号' },
      { key: 'name', label: '姓名' },
      { key: 'phone', label: '手机号' },
      { key: 'company', label: '来访单位' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'visitor_no', label: '访客编号', required: true },
      { key: 'name', label: '姓名', required: true },
      { key: 'phone', label: '手机号' },
      { key: 'company', label: '来访单位' },
      { key: 'status', label: '状态', type: 'select', options: statusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { status: 'ACTIVE' },
  },
  devices: {
    title: 'POS 设备',
    description: '维护餐厅和档口设备资料，阶段 1 只管理基础信息和设备状态。',
    endpoint: '/api/v1/devices',
    idField: 'id',
    statusOptions: deviceStatusOptions,
    columns: [
      { key: 'device_code', label: '设备编码' },
      { key: 'device_name', label: '设备名称' },
      { key: 'canteen_id', label: '餐厅', type: 'reference', referenceKey: 'canteens' },
      { key: 'stall_id', label: '档口', type: 'reference', referenceKey: 'stalls' },
      { key: 'device_type', label: '设备类型' },
      { key: 'status', label: '状态', type: 'status' },
    ],
    fields: [
      { key: 'device_code', label: '设备编码', required: true },
      { key: 'device_name', label: '设备名称', required: true },
      { key: 'canteen_id', label: '餐厅', type: 'reference', reference: canteenReference, required: true },
      { key: 'stall_id', label: '档口', type: 'reference', reference: { ...stallReference, placeholder: '不绑定档口' } },
      {
        key: 'device_type',
        label: '设备类型',
        type: 'select',
        options: [
          { label: 'POS', value: 'POS' },
          { label: '自助终端', value: 'SELF_SERVICE' },
          { label: '移动终端', value: 'MOBILE_TERMINAL' },
        ],
      },
      { key: 'ip_address', label: 'IP 地址' },
      { key: 'location', label: '设备位置' },
      { key: 'status', label: '状态', type: 'select', options: deviceStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    emptyRecord: { device_type: 'POS', status: 'OFFLINE' },
  },
};
